# Generated by Django 5.0.6 on 2024-07-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('generator', '0001_initial'), ('generator', '0002_remove_course_code_course_number'), ('generator', '0003_alter_schedule_score'), ('generator', '0004_alter_schedule_score'), ('generator', '0005_alter_course_title')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('HM', 'MUDD'), ('KS', 'SCRIPPS'), ('CM', 'CMC'), ('PO', 'POMONA'), ('PZ', 'PITZER'), ('XX', 'Other')], default='HM', max_length=2, verbose_name='Offering campus')),
                ('code', models.CharField(max_length=4, verbose_name='Numerical course code')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Course title')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Department Name')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Department code')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='Priority level')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.department'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Section number')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.course')),
            ],
        ),
        migrations.CreateModel(
            name='Occurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday')], max_length=1, verbose_name='Day of the week')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(default=0, max_length=4, verbose_name='Course number'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Priority score')),
                ('as_of', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last scored')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sections', models.ManyToManyField(to='generator.section')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Course title'),
            preserve_default=False,
        ),
    ]
