# Generated by Django 5.0.6 on 2024-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_squashed_0005_alter_course_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepriority',
            options={'verbose_name_plural': 'Course Priorities'},
        ),
        migrations.AddField(
            model_name='coursepriority',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='Course is mandatory'),
        ),
        migrations.AlterField(
            model_name='coursepriority',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Priority level'),
        ),
    ]
