# Generated by Django 5.0.6 on 2024-07-07 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_schedule_options_alter_schedule_as_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('campus', 'department', 'number'), name='unique_course'),
        ),
        migrations.AddConstraint(
            model_name='coursepriority',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_priority'),
        ),
        migrations.AddConstraint(
            model_name='occurance',
            constraint=models.UniqueConstraint(fields=('section', 'day'), name='unique_occurance'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='unique_section'),
        ),
    ]
