# Generated by Django 5.0.6 on 2024-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_course_unique_course_coursepriority_unique_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Is a favorite schedule of its owner'),
        ),
    ]
