# Generated by Django 5.0.6 on 2024-07-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_alter_coursepriority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='as_of',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last scored'),
        ),
    ]
